# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myContentExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myContentExtension

end

target 'skripsiDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for skripsiDemo
  pod ‘Firebase/Core’
  pod ‘Firebase/Database’
  pod ‘GooglePlaces’
  pod ‘GooglePlacePicker’
  pod ‘GoogleMaps’
  pod ‘SwiftyJSON’


  target 'skripsiDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'skripsiDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
